# basic options
title: My awesome title
author: George Crane
email: georgecrane@mac.com
description: My wonderful site
twitter_username: grcrane
github_username:  grcrane

# Build settings
markdown: kramdown
theme: jekyll-theme-slate