# basic options

pages_list:  
  Home: '/'  
  SquareSpace: '/styles.html'
  About: '/javascript.html'
  Editor: '/editor.html'
  Admin: '/admin.html'

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
