# basic options

pages_list:  
  Home: '/'  
  SquareSpace: '/squarespace.html'
  About: '/about.html'
  Editor: '/editor.html'
  Admin: '/admin.html'
  Test: 
    About: '/about.html'
    Editor: '/editor.html'

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
