# basic options

pages_list:  
  Home: '/'  
  Components: '/components.html'
  Code: 
    Overview: '/code_overview.html'
    Styles: '/styles.html'
    JavaScript: '/javascript.html'
    Header: '/header_code.html'
    Footer: '/footer_code.html'
  Editor: '/editor.html'
  Admin: '/admin.html'

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
