# basic options

pages_list:  
  Home: '/'  
  Components: '/components.html'
  Code: 
    Styles: '/styles.html'
    JavaScript: '/javascript.html'
  Editor: '/editor.html'
  Admin: '/admin.html'

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
