# basic options

pages_list:  
  Home: '/'  
  SquareSpace: 
    name: 'xyz'  
  About: '/about.html'
  Editor: '/editor.html'
  Admin: '/admin.html'

 
# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
