# basic options

pages_list:  
  Home: '/Docs/'     
  About: '/Docs/about.html'
  Editor: '/Docs/editor.html'
  Admin: '/Docs/admin.html'

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
